-- Create the openproject_timeentries table
-- This table stores time entries synced from OpenProject via the Edge Function.
-- The 'public' schema is standard for Supabase projects and is required for the default Edge Function configuration.

create table if not exists public.openproject_timeentries (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  timeentry_id bigint not null,
  date_spent date not null,
  "user" character varying not null,
  activity character varying not null,
  work_package text not null,
  comment text null,
  project character varying not null,
  hours numeric null,
  constraint openproject_timeentries_pkey primary key (id),
  constraint unique_timeentry_id unique (timeentry_id)
) tablespace pg_default;

-- Add indexes for common search patterns
create index if not exists idx_openproject_timeentries_date_spent on public.openproject_timeentries (date_spent);
create index if not exists idx_openproject_timeentries_user on public.openproject_timeentries ("user");
create index if not exists idx_openproject_timeentries_project on public.openproject_timeentries (project);
